


<?php
$translations = [
    'home' => 'Home',
    'about' => 'About Us',
    'products' => 'Products',
    'original' => 'Original Flavor',
    'coffee' => 'Coffee Flavor',
    'chocolate' => 'Chocolate Flavor',
    'contact' => 'Contact Us',
    'language' => 'Language',
    'login' => 'Login',
    'register' => 'Register',
    'dashboard' => 'Dashboard',
    'logout' => 'Logout',
    'guest' => '[Guest]',
    'order' => 'Order Now!',
    'title' => 'Vision and Mission',
    'vision' => 'Advancing and empowering women in the family and national economy, as well as reviving traditional culinary heritage to be recognized and loved by the younger generation.',
    'mission1' => 'Continue to innovate and improve product quality to bring traditional food that remains relevant to present tastes..',
    'mission2' => 'Providing products that prioritize customer satisfaction, by maintaining the authenticity of the taste while introducing jadoel snacks to young people.',
    'mission3' => 'Making a positive impact on women empowerment through sustainable economic opportunities in the food industry.',
    'showcase' => 'Our Products',
    'desc1' => 'Classic and delicious',
    'desc2' => 'A hint of coffee for the perfect crunch.',
    'desc3' => 'Rich and indulgent chocolate taste.',
    'slogan' => 'Traditional And Legendary Betawi Specialty Food',
    'philosophy' => 'Philosophy of Ning Nong',
    'philosophy2' => 'The name Ning Nong is born from the union of two simple yet meaningful words.',
    'philosophy3' => '"Ning" is derived from the name of our founder, Mrs. Ningsih, as a tribute to her dedication and passion in establishing our company.',
    'philosophy4' => '"Nong" is a term of endearment for young girls in the Banten region, reflecting the warmth, closeness, and affection we strive to infuse in every product.',
    'philosophy5' => 'Through the Ning Nong brand, we aspire for our traditional delicacy, Kembang Goyang, to not only be a delightful treat but also a source of joy and warmth for everyone who experiences it. Our hope is to cultivate a deep appreciation for local products, especially the signature Kue Kembang Goyang from Tangerang, ensuring it remains a cherished cultural treasure for generations to come.',
    'profile' => 'Ning Nong Company Profile',
    'desc4' => '<b> Kue Kembang Goyang Ning Nong</b> was established back in <b>January 5 2020</b>. We believe that traditional flavors should be enjoyed by everyone, anytime, anywhere. Specializing in premium-quality Kembang Goyang, we take pride in crafting a snack that is not only delicious but also safe and inclusive for all.',
    'desc5' => 'We use only the finest ingredients and a meticulous production process to ensure that each bite delivers a soft, savory delight. Our kembang goyang is carefully crafted to be:',
    'premium' => '<b>Premium Quality</b> –  Made with high-grade ingredients for a superior taste.',
    'safe' => '<b>Safe for Everyone</b> –  Thoughtfully formulated to be safe for pregnant women and children with autism or disabilities.',
    'joy' => '<b>A Joy to Share</b> –  Perfect for any occasion, whether it is a family gathering, a special celebration, or a simple moment with loved ones.',
    'inspire' => 'Inspired by the rich culinary heritage of Tangerang, we are dedicated to keeping this beloved local snack alive while ensuring it meets modern health and safety standards. Our goal is to make Ning Nong Kembang Goyang a treat that people of all ages can enjoy with confidence.',
    'flavor1' => '<b>Ningnong Kembang Goyang – Chocolate</b>',
    'flavor2' => '<b>Ningnong Kembang Goyang – Coffee</b>',
    'flavor3' => '<b>Ningnong Kembang Goyang – Original</b>',
    'desc'=> 'Description',
    'flavor11' => 'For those with a sweet tooth, the chocolate-flavored Kembang Goyang offers a smooth and rich chocolate taste, perfect for satisfying your chocolate cravings.',
    'flavor22' => 'Infused with the rich taste of coffee, this crispy treat is perfect for coffee lovers looking for a unique snack.',
    'flavor33' => 'The classic Kembang Goyang you have always loved, with a crispy texture and timeless flavor. Perfect for any occasion!',
    'price' => 'Price: Rp. 30.000',
    'weight' => 'Net Weight: 65g',
    'flavor111' => 'Crunchy Kembang Goyang with smooth chocolate taste.',
    'flavor222' => 'A crispy treat with a delightful coffee essence.',
    'flavor333' => 'The classic crispy Kembang Goyang with a timeless taste.',

];
?>

